name: gw3099viz
channels:
  - conda-forge
dependencies:

  - python
  - jupyter
  - jupyterlab
  - panoply
  - paraview
  - qgis
  - ipywidgets
  - trame
  - trame-vtk
  - trame-client
  - trame-server
  - trame-vuetify

   