name: gw3099viz
channels:
  - conda-forge
dependencies:

  - python
  - paraview
  - qgis
  - jupyter
  - jupyterlab
  - panoply
  #- pyvista #pyvista and paraview are incompatible in the same environment


   